infoportugal/wagtail-modeltranslation

wagtail_modeltranslation/models.py
wagtail_modeltranslation/templatetags/modeltranslation.py
wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py

Fixed bug on change Language:
this fix re-writes the method Site.get_site_root_paths() so that cache is not set. In the future, think of a way to add cache for each language.

fixed bug when change language

---

AUTHORS.rst
README.rst
docs/AUTHORS.rst
docs/Advanced Settings.rst
docs/CHANGELOG.rst
docs/Configuration.rst
docs/Installation.rst
docs/Introduction.rst
docs/Multilingual Manager.rst
docs/Registering Models.rst
docs/Usage.rst
docs/index.rst

This is the documentation first edition with a link to readthedoc.

wagtail-modeltranslation documentation

---

wagtail_modeltranslation/models.py

AttributeError was: no attribute 'panels' when using InlinePanel
https://github.com/infoportugal/wagtail-modeltranslation/issues/30

Add workaround for InlinePanel AttributeError

---

wagtail_modeltranslation/models.py

try to fix issue  #40 . 
so zh-hant   en-us will work correctly

use build_localized_fieldname insetead using "%s_%s" only

---

README.rst
docs/CHANGELOG.rst
docs/Installation.rst
docs/Registering Models.rst
docs/Usage.rst

Changed
**from wagtail_modeltranslation.translator import TranslationOptions**
To
**from wagtail_modeltranslation.translation import TranslationOptions**
in docs

update documentation 

---

wagtail_modeltranslation/models.py
wagtail_modeltranslation/patch_wagtailadmin.py
wagtail_modeltranslation/templatetags/modeltranslation.py
wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py
wagtail_modeltranslation/wagtail_hooks.py

A couple fixes so 0.5.x works correctly under Python 3.X
https://github.com/infoportugal/wagtail-modeltranslation/issues/73

[FIX] Compatibility Fixes for Python3

---

docs/Installation.rst

Based on issue #126, updates translation.py imports to reflect latest changes

#126, Docs: fix translation.py example

---

wagtail_modeltranslation/patch_wagtailadmin.py
wagtail_modeltranslation/tests/tests.py

Fixes #145 
This PR contains:
- a failing test for `set_url_path()`
- a patch for `save()` that checks if `slug_xx` changed and ensures `set_url_path()` executes if it's required

 Patch save() so we ensure set_url_path is called if slug_xx changes (Fixes #145)

---

.travis.yml
setup.py

By adding latest `django-modeltranslation` master commit as dependency. This is good in the short term for continuous integration but a bad idea for a version release. Releases should only depend on other packages' versions, not commits.

Make experimental build on travis

---

README.rst
docs/advanced settings.rst
runtests.py
wagtail_modeltranslation/patch_wagtailadmin.py
wagtail_modeltranslation/settings.py
wagtail_modeltranslation/tests/tests.py

Since it's no longer relevant and update docs accordingly.
Reverts PR #142.

Remove slug .pre_save() patch 

---

setup.py

https://www.python.org/dev/peps/pep-0508/
otherwise pipenv cant install this package correctly

lets be pep compliant

---

Makefile
Pipfile
Pipfile.lock
setup.cfg
setup.py
wagtail_modeltranslation/__init__.py

I added a makefile which can clean and release a new version of wagtail-modeltranslation.
Just type `make release` into you console.

added Makefile for easy releases

---

wagtail_modeltranslation/patch_wagtailadmin.py
wagtail_modeltranslation/tests/models.py
wagtail_modeltranslation/tests/tests.py
wagtail_modeltranslation/tests/translation.py

This resolve #210 
@dmarcelino and @Alexandre27 can you please take a look?
Cheers

Hide old fields for snippets without panels defenition

---

.gitignore
wagtail_modeltranslation/static/wagtail_modeltranslation/js/wagtail_translated_slugs.js
wagtail_modeltranslation/wagtail_hooks.py

Populate slug not translated

---

wagtail_modeltranslation/wagtail_hooks.py

Very small change. This lets the static files play nice with more complex StaticFilesStorage classes.
Let me know if you have any comments.

Replace direct use of STATIC_URL with static templatetag

---

.travis.yml

I updated the travis-ci configuration file to include the latest python and wagtail versions, plus I added mysql & postresql as services. Otherwise the Travis build faild for me.

Updated travis-ci configuration

---

wagtail_modeltranslation/wagtail_hooks.py

Load static files with django static templatetag

---

wagtail_modeltranslation/wagtail_hooks.py

Hello,
This one was easy to fix.
Cheers
Cedric

Fix #318 ImportError after wagtail update to 2.11

---

pyproject.toml
wagtail_modeltranslation/patch_wagtailadmin.py
wagtail_modeltranslation/static/wagtail_modeltranslation/css/admin_patch.css
wagtail_modeltranslation/static/wagtail_modeltranslation/js/language_toggles.js
wagtail_modeltranslation/wagtail_hooks.py

Wagtail 4 Support

---

AUTHORS.rst

Included @jorenham in AUTHORS.rst

---

.github/workflows/python-package.yml
pyproject.toml
wagtail_modeltranslation/patch_wagtailadmin.py

Fix inherited fields when using django-modeltranslation >= 0.19

---

wagtail_modeltranslation/static/wagtail_modeltranslation/js/copy_stream_fields.js

Change prefix for extractInputId function to match prefix in html tag id attribute.
this should fix [issue #441](https://github.com/infoportugal/wagtail-modeltranslation/issues/441)

fix extractInputId function
