wagtail_modeltranslation/models.py
Resolves Issue #36 
General Problem was, that when a page was edited, the url_paths from subpages where overwritten. 
The method „set_url_path“ is called in "as_page_object()" with a non specific parent page class -> so "parent_url_path" is always the one of the default language
=> #36 Fixed URL property return None 

.travis.yml, tox.ini, wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/tests/tests.py
Fixes #79 by checking the normal slug field on sibling models that aren't patched.
=> Do not check translated slugs on non-translated models + add Tox+Travis support

.travis.yml, tox.ini, wagtail_modeltranslation/static/modeltranslation/js/copy_stream_fields.js, wagtail_modeltranslation/tests/tests.py, wagtail_modeltranslation/wagtail_hooks.py
Changed functionality to copy StreamFields to use POST instead of GET requests, as POST requests normally have a higher size limit than GET requests.
=> Copy content of streamfield fails with 414 Request-URI Too Long

wagtail_modeltranslation/patch_wagtailadmin.py
When patching page models `patch_wagtailadmin.py` includes an extra `.children`. This addresses #107 
This PR removes the extra `.children` for tabs from `model.edit_handler`
=> Remove extraneous .children reference

wagtail_modeltranslation/patch_wagtailadmin.py
The stock `page.route` function is overridden when a developer adds the `RoutablePageMixin` mixin to a `Page` model. The `RoutablePageMixin.route` function verifies that a page has additional routes and returns the appropriate routing to the user. The code can be added to the `wagtail-modeltranslation` patched `_new_route` function without interfering and enables the use of `RoutablePages`.
=> Added routing for RoutablePages

wagtail_modeltranslation/management/commands/set_translation_url_paths.py, wagtail_modeltranslation/management/commands/update_translation_fields.py
BaseCommand expects `handle` and not `handle_noargs`
=> rename handle_noargs to handle in management commands

wagtail_modeltranslation/patch_wagtailadmin.py
without this fix translated slugs are not retrieved as expected, because translated version are available on specific page.
=> [fix] i18n slugs required specific page in order to retrieve good url

docs/advanced settings.rst, runtests.py, wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/settings.py, wagtail_modeltranslation/tests/tests.py
This is my proposed solution for issue #141.
This solution only impacts the original `slug` field by patching its `pre_save()` method which is called right before saving the slug to DB. By patching `pre_save()` the impact is minimal. The translation slug fields are left untouched and accessing `model.slug` has the same behaviour as before.
In brief, this PR has:
- Failing tests that this change addresses (`test_original_slug_update`)
- Sanity tests to ensure nothing is broken by this change (`test_relative_url`)
- `pre_save()` patch
- New setting `WAGTAILMODELTRANSLATION_ORIGINAL_SLUG_LANGUAGE` and respective documentation.
Let me know if you need me to make any changes.
=> #141: Ensure original slug field is always saved in the same language

wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/tests/models.py, wagtail_modeltranslation/tests/tests.py, wagtail_modeltranslation/tests/translation.py
This PR builds on top of PR  #146, so please review that one first.
This PR fixes issue #147, check it for more details.
Mimicking Wagtail core's `Page._update_descendant_url_paths()` this PR includes a similar SQL query to update descendant pages with localized  URL paths. The query was tested in Postgres and SQLite but not MySQL or MS SQL. I would appreciate if someone can volunteer to test those 2 vendors.
This is more efficient than running `child.save()` for every descendant.
=>  Fixes descendant_url_path on page.save()

wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/tests/models.py, wagtail_modeltranslation/tests/tests.py, wagtail_modeltranslation/tests/translation.py, wagtail_modeltranslation/tests/util.py
Follow up to PR #150.
For each `Page.specific` call removed a working test was added to ensure nothing would break.
=> Remove .specific call to save DB queries

wagtail_modeltranslation/management/commands/set_translation_url_paths.py, wagtail_modeltranslation/tests/tests.py
Includes:
1. Working test for `set_translation_url_paths`
2. Changes `set_translation_url_paths` to remove any `.specific` calls and makes it simpler
=> Remove .specific calls from set_translation_url_paths command

.gitignore, docs/template tags.rst, wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py
`get_available_languages_wmt`:
Use this template tag to get the current languages from MODELTRANSLATION_LANGUAGES (or LANGUAGES) from your setting file (or the default settings).
It's the same principle as `get_available_languages`
https://docs.djangoproject.com/fr/1.11/topics/i18n/translation/
=> New tag: 'get_available_languages_wmt'. 

wagtail_modeltranslation/patch_wagtailadmin.py
Since wagtail 1.12 there's a new deprecation warning:
```
RemovedInWagtail113Warning: <class 'a.models.C'>.relative_url should accept a 'request' keyword argument.
```
See [wagtail related documentation](http://docs.wagtail.io/en/v1.11/reference/pages/model_reference.html#wagtail.wagtailcore.models.Page.relative_url)
=> relative_url should accept a 'request' keyword argument.

wagtail_modeltranslation/management/commands/update_translation_fields.py
Addresses issue #103.
Key changes:
- No more raw queries to DB;
- Fetches original field value using `obj.__dict__.get(field_name)` as suggested by modeltranslation [docs](http://django-modeltranslation.readthedocs.io/en/latest/usage.html#the-state-of-the-original-field);
- Monkey patches `Page.full_clean()` to avoid validation errors due to 'slug_xx' and 'title_xx' absences. Note that Django's `Model.save()` itself does not call `full_clean()`, it's `Page.save()` that does it. More about this [here](https://github.com/wagtail/wagtail/issues/3511#issuecomment-339614011) and [here](https://code.djangoproject.com/ticket/13100#comment:2).
Tested with django v1.10, wagtail v1.6.3 and django-modeltranslation v0.12.1.
=> Fix update_translation_fields command

wagtail_modeltranslation/management/commands/makemigrations_translation.py
@DiogoMarques29, I believe I found a solution for the issue you've raised in https://github.com/infoportugal/wagtail-modeltranslation/pull/150#issuecomment-354156263. Essentially this fools `MigrationAutodetector` to think nothing's changed between the old version of Page and the new one.
The advantage I see in this strategy over relying on `if 'makemigrations' in sys.argv:` is that `makemigrations` can safely be used programmatically.
=> Fix makemigrations bug when Page has dependencies

.travis.yml, wagtail_modeltranslation/patch_wagtailadmin.py
This PR patches `Page._update_descendant_url_paths()` to add `.rewrite(False)` to its queryset. It also updates `_localized_update_descendant_url_paths()` to replace raw SQL for a queryset inspired on Wagtail's 1.13 changes.
Travis config was updated to include Wagtail 1.10-1.13 versions and Python 3.3 was replaced for 3.6 (to match Wagtail's own tests).
Note, travis build is taking a considerable amount of time, we should consider dropping some Wagtail or Python versions. Perhaps after releasing v0.8 final.
=> Add support for Wagtail 1.13

wagtail_modeltranslation/patch_wagtailadmin.py
These had been removed before but were reintroduced during `experimental` branch merge.
=> Remove _new_relative_url and _new_url methods

wagtail_modeltranslation/translation.py
This was apparently done by accident on https://github.com/infoportugal/wagtail-modeltranslation/commit/333c392dc8139e0a2cd3256daed56edc9c064142#diff-82b490ec281e50fa1b6e8f2bc765ae3dR10, no reason for `PageTR` to have a meta class with `managed = False`.
=> Remove extraneous Meta class from PageTR

.travis.yml
This PR:
1. Reduces the number of travis jobs by using [matrix include](https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs);
2. Adds jobs to test latest wagtail version against MySQL and Postgres;
3. Reintroduces one python 3.3 job against the latest Wagtail version that used it in tests - Wagtail 1.9
While this strategy is not as exhaustive as running every combination of Python with all wagtail versions I believe it to be a better balance of time and coverage. Build time was reduced from close to 1h to 21 min.
=> Travis: reduce number of jobs from 40 to 15

README.rst, docs/Installation.rst
Update docs:
- sync README with Installation.rst
- Replace TranslationOption with TranslationOptions
- Update examples with latest Django syntax:
- MIDDLEWARE instead of MIDDLEWARE_CLASSES
- _('language') instead of u'language'
@DiogoMarques29, I've noticed README wasn't quite in sync with Installation.rst, this PR fixes that and a few other things. Please review.
=> Update docs: sync README with Installation

setup.py
Since `modeltranslation` v0.12.2 has been released (https://github.com/deschler/django-modeltranslation/issues/436#issuecomment-360767266), let's use it. Drops dependency-links and bumps `wagtail-modeltranslation` to v0.8.
=> Update django-modeltranslation to v0.12.2 and bump version to 0.8

wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/tests/models.py, wagtail_modeltranslation/tests/tests.py
Fixes #170 
Ensure localized StreamFields remain optional as per [django-modeltranslation docs](http://django-modeltranslation.readthedocs.io/en/latest/registration.html?highlight=blank#required-fields) for Wagtail 1.12 and above.
=> Make localized StreamField optional (Wagtail >= 1.12)

wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py
Fixes #176.
* Remove call to `context['request']` to prevent KeyError;
* Replace it with call to `pageurl(context, page)` mimicking Wagtail's default behaviour (see [wagtailcore_tags.py#L37-L39](https://github.com/wagtail/wagtail/blob/master/wagtail/core/templatetags/wagtailcore_tags.py#L37-L39)), which does the exception handling.
* Does not include a failing test since the behaviour is mostly unchanged and mimics default wagtail code.
=> Make slugurl_trans tag resilient to missing request

.travis.yml
I've noticed that the current travis console output is not very friendly in what regards figuring out Django's version. This PR helps with that.
Make clearer which django version is being tested:
- by printing it to the console;
- by outputting `pip install $WAGTAIL` output.
- Also remove `--process-dependency-links` as it's no longer needed.
Travis console example ([link](https://travis-ci.org/dmarcelino/wagtail-modeltranslation/jobs/347372362#L434)):
=> Travis: make clear which django version is used

.travis.yml, runtests.py, setup.py, wagtail_modeltranslation/management/commands/set_translation_url_paths.py, wagtail_modeltranslation/management/commands/sync_page_translation_fields.py, wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py, wagtail_modeltranslation/tests/models.py, wagtail_modeltranslation/tests/tests.py, wagtail_modeltranslation/tests/urls.py, wagtail_modeltranslation/tests/util.py, wagtail_modeltranslation/translation.py, wagtail_modeltranslation/wagtail_hooks.py
This PR replaces PR #180 and fixes #169.
Also, this PR was branched from PR #181, so please merge that one first.
The changes here are essentially cherry picks from PR #180, I've picked the changes related to Wagtail2 and ignored any Django 2 specific changes. Those should be handled on a separate PR and can only be done after `django-modeltranslation` releases a new version (see deschler/django-modeltranslation#436).
Summary of changes:
- Ensure wagtail version < 2 (credit to @Jason-Abbott)
- Wagtail 2 support with backwards compatibility (credit to @stuaxo)
- Update travis.yml to test wagtail 2
=> Add support for Wagtail 2

setup.py
As @stuaxo pointed out in https://github.com/infoportugal/wagtail-modeltranslation/pull/185#issuecomment-375334755, PR #185 wrongfully set `wagtail<2` instead of `Django<2`. This means that `0.8.1` doesn't allow for Wagtail2 to be used and doesn't enforce Django to be set below v2.
This PR fixes things by changing `setup.py` to `install_requires=['Django(<2.0)', 'wagtail(>=1.4)', 'django-modeltranslation(>=0.12.2)'],`
@DiogoMarques29, @tiagofmc please review and consider making a new release so people can use `wagtail-modeltranslation` with `wagtail` 2.
=> Force django<2 while allowing Wagtail 2

.gitignore, wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/tests/tests.py, wagtail_modeltranslation/tests/util.py
Fixes #195
In https://github.com/infoportugal/wagtail-modeltranslation/issues/195#issuecomment-376732049 @dwasyl has uncovered that `Site.get_site_root_paths()` returns a cached copy of site root paths which can be of the wrong language causing `Page.url` to return `None`.
Changes in this PR:
- Change `PageFactory.create_page_tree()` to return a page structure that better mimics Wagtail's live behaviour
- Failing test
- ~~Decorator to clear the cached sites if the language changed.~~
- Monkey patches `Page._get_site_root_paths()` so it returns site root paths for the current language
- For Wagtail<1.11 monkey patch `Page.get_url_parts()` with the most recent code which calls `Page._get_site_root_paths()`
=> _get_site_root_paths: clear cache when changing languages

wagtail_modeltranslation/static/wagtail_modeltranslation/js/wagtail_translated_slugs.js
This change correctly downcodes diacritics to ASCII if user has WAGTAIL_ALLOW_UNICODE_SLUGS = False (e.g. abčďéfg -> abcdefg)
Without this change, the slug simply strips all diacritics which is not ideal (e.g. abčďěfg -> abfg)
cleanForSlug function uses URLify if the second parameter is true:
https://github.com/wagtail/wagtail/blob/0dacda913337d6a24c962b906811b857679831b2/wagtail/admin/static_src/wagtailadmin/js/page-editor.js#L240
Vanilla Wagtail correctly calls cleanForSlug with useURLify set to true (when following title).
Previously cleanForSlug only had one parameter, but AFAIK javascript doesn't care if a function is called with more parameters than specified.
=> Fix diacritics downcoding in slugs

docs/Installation.rst
Updated documentation, added missing 'wagtail_modeltranslation.migrate' in Quick Setup section.
=> Add migrate module to INSTALLED_APPS setting list

tox.ini, wagtail_modeltranslation/static/wagtail_modeltranslation/js/copy_stream_fields.js, wagtail_modeltranslation/static/wagtail_modeltranslation/js/version_compare.js, wagtail_modeltranslation/wagtail_hooks.py
Wagtail 2.6 introduced some changes in the admin layout.
Wagtail-modeltranslation now fails to add the copy buttons to the div containing the titles, this PR fixes this issue, trying to leave things unchanged for older versions of Wagtail.
=> Fixed missing copy buttons for Wagtail 2.6.x.

wagtail_modeltranslation/templates/modeltranslation_copy.html
This fixes an issue where the page selection widget on the copy form fails to function.
wagtail.admin.views.pages.copy() relies on a `CopyForm` which uses an `AdminPageChooser` widget for the `new_parent_page` field. `AdminPageChooser` relies on the inclusion of JS files to function correctly, as referenced in the `media` properly below.
The copy template thus requires the inclusion of `{{ form.media.js }}` to keep parity with the default Wagtail copy template (see: wagtailadmin/pages/copy.html).
```
@property
def media(self):
return forms.Media(js=[
versioned_static('wagtailadmin/js/page-chooser-modal.js'),
versioned_static('wagtailadmin/js/page-chooser.js'),
])
```
=> Render form JS script tags in copy template

wagtail_modeltranslation/patch_wagtailadmin.py
In a project I am working on I needed to subclass the index.SearchField- but this field wasn't handled by wagtail-modeltranslation.
The current code in wagtail-modeltranslation compares the class name instead of the instance type- i changed it, so that subclasses of SearchField are patched, too.
=> Patch subclasses of SearchField for the search index

wagtail_modeltranslation/patch_wagtailadmin_forms.py, wagtail_modeltranslation/templates/modeltranslation_copy.html, wagtail_modeltranslation/wagtail_hooks.py
This directly addresses issue #283.
This fixes a bug where the "Copy Page" form would always show multiple language fields for the `new_slug` field even if `WAGTAILMODELTRANSLATION_TRANSLATE_SLUGS` is set to `False` in your project.
=> Bugfix for "Copy Page" form not working when TRANSLATE_SLUGS = False

wagtail_modeltranslation/static/wagtail_modeltranslation/js/language_toggles.js
While using [CodeRed](https://docs.coderedcorp.com/cms/stable/how_to/translation.html) I stumbled on their issue [#317](https://github.com/coderedcorp/coderedcms/issues/317), where language toggle buttons do not work and make the page reload.
This happens because the click listeners are added to **each** top-level element, instead of just the first one (CodeRed adds multiple `.tab-content` elements, which break the current code).
The proposed fix is to add the toggle buttons to just the first `.tab-element` of the page.
=> Fix toggle compatibility for CodeRed

wagtail_modeltranslation/wagtail_hooks.py
Commit 514f589 ("Hotfix: undefined variables in JS due to bad merge")
overquoted translate_slugs, so that Javascript doesn't get the boolean
values `true` or `false`, but the strings `'true'` or `'false'` instead,
which both evalute to true in the Javascript code.
As an effect, slugs are no longer autocreated for the language agnostic
"#id_slug" field even if TRANSLATE_SLUGS is not set or set to False. If
the user doesn't manually enter a slug string, the page fails validation
with "This field is required."
Remove quotes from transate_slugs.
Fixes infoportugal/wagtail-modeltranslation#293
=> Fix autocreation of slugs

wagtail_modeltranslation/wagtail_hooks.py
With a setting like this:
LANGUAGE_CODE = 'en-us'
LANGUAGES = (
('en', _('English')),
('de', _('German')),
)
LANGUAGE_CODE includes a country and is not enumerated in LANGUAGES.
This causes the autogeneration of (untranslated) slugs to fail and all
language toggles to default to off.
Use MODELTRANSLATION_DEFAULT_LANGUAGE instead of LANGUAGE_CODE.
MODELTRANSLATION_DEFAULT_LANGUAGE is defaulted to the first element of
MODELTRANSLATION_LANGUAGES which is defaulted to LANGUAGES [1].
If the user overwrites, it is verified, that
MODELTRANSLATION_DEFAULT_LANGUAGE is one of the languages availabe in
MODELTRANSLATION_LANGUAGES [1].
This fixes the problem mentioned in #287 (comment), although it is not the original topic of #287
[1] https://github.com/deschler/django-modeltranslation/blob/master/mod …
=> Use DEFAULT_LANGUAGE from django-modeltranslation

wagtail_modeltranslation/static/wagtail_modeltranslation/js/language_toggles.js
Adds an event dispatch at the end of `buildSets` so that third party JS that needs to run "on page load" can also listen for this event in order to do things to the DOM based on a knowledge that locale fields may now be hidden.
See related issue https://github.com/infoportugal/wagtail-modeltranslation/issues/306
=> Add "finished building" event for third party JS to hook into

wagtail_modeltranslation/patch_wagtailadmin.py
It resolves an issue where nested inline panels would raise
an error as the property would not exists on the original model.
Resolves: #300
=> Use the current patching model for the inline panel patch

wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py
Which would result in sites crashing completely if {% change_lang ... %} was used in the 404 template itself, or in it's base, , as it seems 404 are rendered before redirecting from `/` to `/en`
=> fix #315 where change_lang tag would if used on a 404

docs/advanced settings.rst, wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/settings.py
This adds a CUSTOM_INLINE_PANELS settings, that works exactly like the other two CUSTOM_*_PANELS.
I needed this to have wagtail-modeltranslation work with wagtail-multi-upload, which provides a panel that inherits InlinePanel, that didn't got translated.
What do you think ?
Worth noting that it doesn't work 100% with wagtail-multi-upload, as all fields are still displayed when adding multiple images at once, but that's probably an issue that must be fixed on their side (missing some "inline added" javascript signal or something).
=> added CUSTOM_INLINE_PANELS setting

wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py
Currently when using the template tag `change_lang` and the request url resolves to `wagtail_serve`, a value of `None` is returned.
The code activates the target language, retrieves the page url, reverts the language, and returns the result.
When debugging the `url` attribute of `page` was `None`. Internally the base Wagtail Page class defines `url` with the builtin `property` (not decorated) method and returns `get_url`.
My proposed change refactors use of the property to calling `get_url` directly. I have not been able to determine why the property returns `None` in this context. There may be a better systemic solution but this solved my issue.
=> Fix issue with `change_lang` template tag

wagtail_modeltranslation/static/wagtail_modeltranslation/js/copy_stream_fields.js
In recent wagtail versions, the streamfield input elements `id`'s have changed, and the outer `div` selector does not work anymore (again). This is a quick fix that modifies the `id` values (so that the buttons remain functional in a backwards-compatible way) and fixes the selector.
This fixes https://github.com/infoportugal/wagtail-modeltranslation/issues/337
=> "Copy content from: ..." buttons fix

wagtail_modeltranslation/patch_wagtailadmin.py
In wagtail >=2.16 wagtail-modeltranslation causes a fatal bug on all wagtail pages and in wagtailadmin: `AttributeError: 'tuple' object has no attribute 'root_path'`
=> Fatal bugfix for Wagtail>=2.16 

wagtail_modeltranslation/static/wagtail_modeltranslation/js/wagtail_translated_slugs.js
This solves the following issue #390 that generated after Wagtail removed `cleanForSlug` from `window`:
https://github.com/wagtail/wagtail/commit/a81242ca860c7c15a36aa11c2093ba63f30d59e7#diff-478b818270e95babc58672eae8842576d8601f181f5780ef7c07c34936c63cd7
Of course this isn't the best approach at it but for now it does the job.
=> Monkey-patch cleanForSlug

.github/workflows/python-package.yml, wagtail_modeltranslation/templates/modeltranslation_copy.html, wagtail_modeltranslation/tests/settings.py, wagtail_modeltranslation/wagtail_hooks.py
Concerns the following Wagtail 5.1 deprecations: 
- https://docs.wagtail.org/en/stable/releases/5.1.html#removed-support-for-python-3-7
- https://docs.wagtail.org/en/stable/releases/5.1.html#insert-editor-css-hook-is-deprecated
- https://docs.wagtail.org/en/stable/releases/5.1.html#shared-include-field-as-li-html-will-be-removed
- https://docs.wagtail.org/en/stable/releases/5.1.html#wagtail-contrib-modeladmin-is-deprecated
=> Fixed deprecated hook for wagtail>=5.1

wagtail_modeltranslation/patch_wagtailadmin.py, wagtail_modeltranslation/static/wagtail_modeltranslation/css/admin_patch.css
- #414 - Simple fix
- #415 - CSS issue
- #416 - Logic error
1. Please test, I don't have the time. 
2. Includes passing `classname = "title"` to `FieldPanel` for consistent styling.
=> Fix TitleFieldPanel patching

wagtail_modeltranslation/patch_wagtailadmin.py
FIX Renaming a parent page breaks the path to children ones ( When a parent slug page update the children path breaks , adding or delete charactere depending the difference between len(new_path_url) and len(old_path_url)
=> FIX Renaming a parent page breaks the path to children ones
